unmapAll
map <c-k> scrollDown
map <c-i> scrollUp
map <c-m-i> scrollToTop
map <c-m-k> scrollToBottom
map <c-a-i> scrollPageUp
map <c-a-k> scrollPageDown
map <c-J> goBack
map <c-L> goForward
map <c-m> Marks.activateCreateMode
map <c-'> Marks.activateGotoMode
map <c-f> LinkHints.activateMode
map <c-F> LinkHints.activateModeToOpenInNewTab
map <c-Y> LinkHints.activateModeToCopyLinkUrl
map <c-y><c-y> copyCurrentUrl
map <c-o> Vomnibar.activateTabSelection
map <c-m-a-J> moveTabLeft
map <c-m-a-L> moveTabRight
map <c-u> goUp
map <c-t> moveTabToNewWindow
# map <m-w> removeTab